# GENERATED BY LOCK2NIX.py
# DO NOT EDIT BY HAND
{fetchzip, runCommand} : rec {
  _fe_analyzer_shared = fetchzip {
    sha256 = "15fh9ka41dw4qsynv07msq4i243fibprcmafdygw5x88f7m55fq3";
    url = "https://pub.dartlang.org/packages/_fe_analyzer_shared/versions/61.0.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  analyzer = fetchzip {
    sha256 = "0w604zngxwfx0xqxvhbxrhdh04wgm6ad6a1lbwnyvmk57amv44np";
    url = "https://pub.dartlang.org/packages/analyzer/versions/5.13.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  args = fetchzip {
    sha256 = "01ps253280c6dbx0vncw4wga4l2qp1zx779qjj2x06xzb3744zbz";
    url = "https://pub.dartlang.org/packages/args/versions/2.4.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  async = fetchzip {
    sha256 = "0hfgvjajp5c2mw68186hgrk9v5zjhhi149hlhl0fap274p2v1g3q";
    url = "https://pub.dartlang.org/packages/async/versions/2.11.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  boolean_selector = fetchzip {
    sha256 = "0hxq8072hb89q9s91xlz9fvrjxfy7hw6jkdwkph5dp77df841kmj";
    url = "https://pub.dartlang.org/packages/boolean_selector/versions/2.1.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  build = fetchzip {
    sha256 = "1x6nkii6kqy6y7ck0151yfhc9lp2nvbhznnhdi2mxr8afk6jxigd";
    url = "https://pub.dartlang.org/packages/build/versions/2.3.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  build_config = fetchzip {
    sha256 = "092rrbhbdy9fk50jqb1fwj1sfk415fi43irvsd0hk5w90gn8vazj";
    url = "https://pub.dartlang.org/packages/build_config/versions/1.1.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  build_daemon = fetchzip {
    sha256 = "1wn7bq846vgdj62bkh9h25l95xdsndv0jdyw52nyr0591l3bpg3h";
    url = "https://pub.dartlang.org/packages/build_daemon/versions/3.1.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  build_resolvers = fetchzip {
    sha256 = "00h9abhrfmnl0xxziyf6p68sxnbv2ww1c4dhgpnz00mzbmamnq5c";
    url = "https://pub.dartlang.org/packages/build_resolvers/versions/2.3.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  build_runner = fetchzip {
    sha256 = "0b5ha1l6k0gn2swqgqvfy2vl58klf81sxrjnmk0p7rj1wzbqjm7l";
    url = "https://pub.dartlang.org/packages/build_runner/versions/2.3.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  build_runner_core = fetchzip {
    sha256 = "07r1kfy6ylm4i4xrb24ns8l26h4h1lgcskmnf8wvq2rd5d5hq790";
    url = "https://pub.dartlang.org/packages/build_runner_core/versions/7.2.7%2B1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  built_collection = fetchzip {
    sha256 = "0bqjahxr42q84w91nhv3n4cr580l3s3ffx3vgzyyypgqnrck0hv3";
    url = "https://pub.dartlang.org/packages/built_collection/versions/5.1.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  built_value = fetchzip {
    sha256 = "1y84imf9xqqy3gnd5zz9bcln6mycy7qx35r70b0izm31ismlbzkv";
    url = "https://pub.dartlang.org/packages/built_value/versions/8.6.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  checked_yaml = fetchzip {
    sha256 = "1sn01yrmj0pkijn08g3v45c3zmyvdygk9svigkkzybgicdwlkpqs";
    url = "https://pub.dartlang.org/packages/checked_yaml/versions/2.0.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  code_builder = fetchzip {
    sha256 = "1shgl7mxiyv0hhw326yqj2b9jxi1h74qxmsnxf1d1xc6yz766p9a";
    url = "https://pub.dartlang.org/packages/code_builder/versions/4.6.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  collection = fetchzip {
    sha256 = "1mr8j0078c4z9hhckiq8m735rggsazwfprm0w9gisil51vh7j2mk";
    url = "https://pub.dartlang.org/packages/collection/versions/1.18.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  convert = fetchzip {
    sha256 = "0adsigjk3l1c31i6k91p28dqyjlgwiqrs4lky5djrm2scf8k6cri";
    url = "https://pub.dartlang.org/packages/convert/versions/3.1.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  coverage = fetchzip {
    sha256 = "1yy9bgkax5b6kk7qa07p452v82fyj4rl1j03fn366ywyvhfrh6lp";
    url = "https://pub.dartlang.org/packages/coverage/versions/1.6.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  crypto = fetchzip {
    sha256 = "100ai8qa4p3dyvvd60c4xa9p0gm06yh0d68xgcfm3giraad8xmqj";
    url = "https://pub.dartlang.org/packages/crypto/versions/3.0.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  cryptography = fetchzip {
    sha256 = "1yxn9slqq93ri81fbr2nbsinz0mpk9wk39ny076ja8q31d4i8v3f";
    url = "https://pub.dartlang.org/packages/cryptography/versions/2.5.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  dart_style = fetchzip {
    sha256 = "0cjhrb1hs8iw9smmfd0fgnxq3nm0w8sz17l6q6svyz6kif19wk9k";
    url = "https://pub.dartlang.org/packages/dart_style/versions/2.3.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  file = fetchzip {
    sha256 = "0ajcfblf8d4dicp1sgzkbrhd0b0v0d8wl70jsnf5drjck3p3ppk7";
    url = "https://pub.dartlang.org/packages/file/versions/6.1.4.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  fixnum = fetchzip {
    sha256 = "0nqrzj41ys8dpxf1x70r0kfj1avj0f2j2b7498k8kvc0i9c5asz7";
    url = "https://pub.dartlang.org/packages/fixnum/versions/1.1.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  frontend_server_client = fetchzip {
    sha256 = "096v7ycix5hgnk750s1qgykyghl2mymhdkg39jrlk3kbj6xygq5b";
    url = "https://pub.dartlang.org/packages/frontend_server_client/versions/3.2.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  glob = fetchzip {
    sha256 = "0ffab3azx8zkma36mk6wnig8bn8g5g0vjrq2gl21y77rxgw9iqxj";
    url = "https://pub.dartlang.org/packages/glob/versions/2.1.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  graphs = fetchzip {
    sha256 = "0fda0j8y6sq1rc9zpzglrzysl5h49y2ji1wq2lq0wx2c609dxm7f";
    url = "https://pub.dartlang.org/packages/graphs/versions/2.3.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  hex = fetchzip {
    sha256 = "19w3f90mdiy06a6kf8hlwc4jn4cxixkj106kc3g3bis27ar7smkh";
    url = "https://pub.dartlang.org/packages/hex/versions/0.2.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  http_multi_server = fetchzip {
    sha256 = "1zdcm04z85jahb2hs7qs85rh974kw49hffhy9cn1gfda3077dvql";
    url = "https://pub.dartlang.org/packages/http_multi_server/versions/3.2.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  http_parser = fetchzip {
    sha256 = "027c4sjkhkkx3sk1aqs6s4djb87syi9h521qpm1bf21bq3gga5jd";
    url = "https://pub.dartlang.org/packages/http_parser/versions/4.0.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  io = fetchzip {
    sha256 = "101kd0rw26vglmr1m5p130kbrp3k7dk4p5nr77wsbwgg53w8c0d4";
    url = "https://pub.dartlang.org/packages/io/versions/1.0.4.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  js = fetchzip {
    sha256 = "124a9yqrjdw3p4nnirab9hm9ziwraldlw4q5cb3sr0dcrli74qpw";
    url = "https://pub.dartlang.org/packages/js/versions/0.6.7.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  json_annotation = fetchzip {
    sha256 = "1jjw7p8qyqajgdq4jqvxipq5w0qrq9dpi1qmia70pk995akryh6m";
    url = "https://pub.dartlang.org/packages/json_annotation/versions/4.8.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  json_serializable = fetchzip {
    sha256 = "1pmidql9x6s2pbhdx9x20pwqwvwpfkvrz0h0cm1f8pqis76c90hb";
    url = "https://pub.dartlang.org/packages/json_serializable/versions/6.6.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  logging = fetchzip {
    sha256 = "124hfjs66r30p92ndfmy5fymgy66yk9in97h8sq6fi7r78pqyc7g";
    url = "https://pub.dartlang.org/packages/logging/versions/1.2.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  matcher = fetchzip {
    sha256 = "0inznqkrxqnq09lcbwvda3xd07qfm1k3aa6dv1wy39gvci8hybss";
    url = "https://pub.dartlang.org/packages/matcher/versions/0.12.16.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  meta = fetchzip {
    sha256 = "1l3zaz6q2s9mnm7s674xshsfqspy79p5kdbbnc99rf2l76avv4h3";
    url = "https://pub.dartlang.org/packages/meta/versions/1.9.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  mime = fetchzip {
    sha256 = "1dha9z64bsz8xhi0p62vmlyikr8xwbdlrw90hxghmm3rdgd9h25w";
    url = "https://pub.dartlang.org/packages/mime/versions/1.0.4.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  moxlib = fetchzip {
    sha256 = "1qaacmcqhq33grn2nq8sn23ki62dcmw0fqy589xm1zv6w0pzfmsk";
    url = "https://git.polynom.me/api/packages/moxxy/pub/api/packages/moxlib/files/0.2.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  node_preamble = fetchzip {
    sha256 = "12ajg76r9aqmqkavvlxbnb3sszg1szcq3f30badkd0xc25mnhyh8";
    url = "https://pub.dartlang.org/packages/node_preamble/versions/2.0.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  omemo_dart = fetchzip {
    sha256 = "0fhf89ic5mdyld25l6rfb37a1fk1f0f2b4d72xi4r7pvr0ddjhz8";
    url = "https://git.polynom.me/api/packages/PapaTutuWawa/pub/api/packages/omemo_dart/files/0.5.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  package_config = fetchzip {
    sha256 = "1d4l0i4cby344zj45f5shrg2pkw1i1jn03kx0qqh0l7gh1ha7bpc";
    url = "https://pub.dartlang.org/packages/package_config/versions/2.1.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  path = fetchzip {
    sha256 = "1mjdhq2fsz6i9krhp2mnaks2bcw34sa4p7mg0v6njk8dgx2754iv";
    url = "https://pub.dartlang.org/packages/path/versions/1.8.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  pedantic = fetchzip {
    sha256 = "10ch0h3hi6cfwiz2ihfkh6m36m75c0m7fd0wwqaqggffsj2dn8ad";
    url = "https://pub.dartlang.org/packages/pedantic/versions/1.11.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  petitparser = fetchzip {
    sha256 = "19zqrpb1z77aw1k2s8rsxdfxczzv9934g2rdfj2jyiv3pqgdq8gh";
    url = "https://pub.dartlang.org/packages/petitparser/versions/5.4.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  pinenacl = fetchzip {
    sha256 = "0didjgva658z90hbcmhd0y8w1b8v86dp6gabfhylnw1aixl47cxg";
    url = "https://pub.dartlang.org/packages/pinenacl/versions/0.5.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  pool = fetchzip {
    sha256 = "0wmzs46hjszv3ayhr1p5l7xza7q9rkg2q9z4swmhdqmhlz3c50x4";
    url = "https://pub.dartlang.org/packages/pool/versions/1.5.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  protobuf = fetchzip {
    sha256 = "1jriyisf8bnvq5ygjk93mn2yzdlnii7xrhy6aabz54xr3y4dcy9x";
    url = "https://pub.dartlang.org/packages/protobuf/versions/2.1.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  protoc_plugin = fetchzip {
    sha256 = "0hjjd1xkv4s4g1d5n2aza0kdwlbfl2aivq99230m3yml7irn00jk";
    url = "https://pub.dartlang.org/packages/protoc_plugin/versions/20.0.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  pub_semver = fetchzip {
    sha256 = "0wpcfz1crxipbjm18m71pl4vl2ra8vw1n93ff8snr54mmlyfb9z1";
    url = "https://pub.dartlang.org/packages/pub_semver/versions/2.1.4.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  pubspec_parse = fetchzip {
    sha256 = "0dj8sf1w61g7vh1ly3sl690z0nwllzjzbapxswmgsglr0ndcyrs1";
    url = "https://pub.dartlang.org/packages/pubspec_parse/versions/1.2.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  random_string = fetchzip {
    sha256 = "11cjiv75sgldvk3x7w6j77lgi08r6737wm94m3ylabylsr6zdyff";
    url = "https://pub.dartlang.org/packages/random_string/versions/2.3.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  saslprep = fetchzip {
    sha256 = "04lss0xvm6p801p8306jdxg7k0b28kr6n65dz2f57dkca237kcw7";
    url = "https://pub.dartlang.org/packages/saslprep/versions/1.0.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  shelf = fetchzip {
    sha256 = "10yk98nadrgj5d3r3241kdaywjjs1j10mg8gacv80kg1mhcfdrxp";
    url = "https://pub.dartlang.org/packages/shelf/versions/1.4.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  shelf_packages_handler = fetchzip {
    sha256 = "1h8s42nff9ar0xn7yb42m64lpvmqzq8wranqrkkixdnp7w3pmv1x";
    url = "https://pub.dartlang.org/packages/shelf_packages_handler/versions/3.0.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  shelf_static = fetchzip {
    sha256 = "1bcqynn2z2syrigmrclxgg8hjhd1x9742938i62cicbaga6vclaz";
    url = "https://pub.dartlang.org/packages/shelf_static/versions/1.1.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  shelf_web_socket = fetchzip {
    sha256 = "110b5hrqwpnmq16shxxzjmcih5yfs5kh80dn8avfv0xj5iv7n94c";
    url = "https://pub.dartlang.org/packages/shelf_web_socket/versions/1.0.4.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  source_gen = fetchzip {
    sha256 = "1jql5zccv4vnbbvwcpyyvz8l27pg1rviqbp4vrks5313nf4b0kjg";
    url = "https://pub.dartlang.org/packages/source_gen/versions/1.3.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  source_helper = fetchzip {
    sha256 = "0mdd02vhcdcv9n58gzbx2q0bphwj0alz312ca1a8xpkf8jx3y8v4";
    url = "https://pub.dartlang.org/packages/source_helper/versions/1.3.4.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  source_map_stack_trace = fetchzip {
    sha256 = "0b5d4c5n5qd3j8n10gp1khhr508wfl3819bhk6xnl34qxz8n032k";
    url = "https://pub.dartlang.org/packages/source_map_stack_trace/versions/2.1.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  source_maps = fetchzip {
    sha256 = "004lcfka01agxjdw7zjhrffdkisvgx5s61b5gsl8qqk2jd1rswa7";
    url = "https://pub.dartlang.org/packages/source_maps/versions/0.10.12.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  source_span = fetchzip {
    sha256 = "1nybnf7l5chslp4fczhqnrgrhymy844lw7qrj6y08i626dshrd46";
    url = "https://pub.dartlang.org/packages/source_span/versions/1.10.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  stack_trace = fetchzip {
    sha256 = "0xpk2cvmgdh46iwip9jsb54fqx13jnina8pk03akxkmsxvag5izb";
    url = "https://pub.dartlang.org/packages/stack_trace/versions/1.11.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  stream_channel = fetchzip {
    sha256 = "0nrlw6zcscgnn6818krkbgs9qiv3f7q8pa7ljw1bqkrsb7xabm8s";
    url = "https://pub.dartlang.org/packages/stream_channel/versions/2.1.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  stream_transform = fetchzip {
    sha256 = "0jq6767v9ds17i2nd6mdd9i0f7nvsgg3dz74d0v54x66axjgr0gp";
    url = "https://pub.dartlang.org/packages/stream_transform/versions/2.1.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  string_scanner = fetchzip {
    sha256 = "0p1r0v2923avwfg03rk0pmc6f21m0zxpcx6i57xygd25k6hdfi00";
    url = "https://pub.dartlang.org/packages/string_scanner/versions/1.2.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  synchronized = fetchzip {
    sha256 = "1fx1z1p5qkn4qnq24riw5s86vmq645ppg8f74iyv2fc9rvr301ar";
    url = "https://pub.dartlang.org/packages/synchronized/versions/3.1.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  term_glyph = fetchzip {
    sha256 = "1x8nspxaccls0sxjamp703yp55yxdvhj6wg21lzwd296i9rwlxh9";
    url = "https://pub.dartlang.org/packages/term_glyph/versions/1.2.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  test = fetchzip {
    sha256 = "002phlj2pg6nll5hv449izxbqk29zwmwc77d0jx2iimz18dgy2r5";
    url = "https://pub.dartlang.org/packages/test/versions/1.24.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  test_api = fetchzip {
    sha256 = "0as1xcywjrd2zax3cm56qmnac12shf8c1ynnzzjwnggm23f61dxb";
    url = "https://pub.dartlang.org/packages/test_api/versions/0.6.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  test_core = fetchzip {
    sha256 = "1cx2rmz1xzk5z5yh8fpbsrsz4mgjanrw4xvnp0qzdnm2d7vhaq0y";
    url = "https://pub.dartlang.org/packages/test_core/versions/0.5.3.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  timing = fetchzip {
    sha256 = "15jvxsw7v0gwbdlykma60l1qlhlzb3brh6m0sg2bgbfir4l5s9gw";
    url = "https://pub.dartlang.org/packages/timing/versions/1.0.1.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  typed_data = fetchzip {
    sha256 = "0q6ggc52vfpr8kqaq69h757wy942hvgshhnsr2pjdinb4zk2sxl1";
    url = "https://pub.dartlang.org/packages/typed_data/versions/1.3.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  unorm_dart = fetchzip {
    sha256 = "05kyk2764yz14pzgx00i7h5b1lzh8kjqnxspfzyf8z920bcgbz0v";
    url = "https://pub.dartlang.org/packages/unorm_dart/versions/0.2.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  uuid = fetchzip {
    sha256 = "1nh1hxfr6bhyadqqcxrpwrphmm75f1iq4rzfjdwa2486xwlh7vx3";
    url = "https://pub.dartlang.org/packages/uuid/versions/3.0.7.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  very_good_analysis = fetchzip {
    sha256 = "1p2dh8aahbqyyqfzbsxswafgxnmxgisjq2xfp008skyh7imk6sz4";
    url = "https://pub.dartlang.org/packages/very_good_analysis/versions/3.1.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  vm_service = fetchzip {
    sha256 = "15ail7rbaq9ksg73cc0mw2k5imbiidl95yfd4v49k81gp5xmj92w";
    url = "https://pub.dartlang.org/packages/vm_service/versions/11.10.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  watcher = fetchzip {
    sha256 = "1sk7gvwa7s0h4l652qrgbh7l8wyqc6nr6lki8m4rj55720p0fnyg";
    url = "https://pub.dartlang.org/packages/watcher/versions/1.0.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  web_socket_channel = fetchzip {
    sha256 = "0f9441c4zifb5qadpjg319dcilimpkdhfacnkl543802bf8qjn4w";
    url = "https://pub.dartlang.org/packages/web_socket_channel/versions/2.4.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  webkit_inspection_protocol = fetchzip {
    sha256 = "0z400dzw7gf68a3wm95xi2mf461iigkyq6x69xgi7qs3fvpmn3hx";
    url = "https://pub.dartlang.org/packages/webkit_inspection_protocol/versions/1.2.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  xml = fetchzip {
    sha256 = "120azx71gazvrrn07vd83vrffzrhsqnmf9rdjxl73rra9py8ixiy";
    url = "https://pub.dartlang.org/packages/xml/versions/6.3.0.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  yaml = fetchzip {
    sha256 = "0awh9dynbhrlq8zgszaiyxbyyn9b6wyps1zww4z2lx62nbma0pda";
    url = "https://pub.dartlang.org/packages/yaml/versions/3.1.2.tar.gz";
    stripRoot = false;
    extension = "tar.gz";
  };

  pubCache = runCommand "moxxmpp-pub-cache" {} ''
    mkdir -p $out/hosted/pub.dev
    ln -s ${_fe_analyzer_shared} $out/hosted/pub.dev/_fe_analyzer_shared-61.0.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${analyzer} $out/hosted/pub.dev/analyzer-5.13.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${args} $out/hosted/pub.dev/args-2.4.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${async} $out/hosted/pub.dev/async-2.11.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${boolean_selector} $out/hosted/pub.dev/boolean_selector-2.1.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${build} $out/hosted/pub.dev/build-2.3.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${build_config} $out/hosted/pub.dev/build_config-1.1.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${build_daemon} $out/hosted/pub.dev/build_daemon-3.1.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${build_resolvers} $out/hosted/pub.dev/build_resolvers-2.3.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${build_runner} $out/hosted/pub.dev/build_runner-2.3.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${build_runner_core} $out/hosted/pub.dev/build_runner_core-7.2.7+1

    mkdir -p $out/hosted/pub.dev
    ln -s ${built_collection} $out/hosted/pub.dev/built_collection-5.1.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${built_value} $out/hosted/pub.dev/built_value-8.6.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${checked_yaml} $out/hosted/pub.dev/checked_yaml-2.0.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${code_builder} $out/hosted/pub.dev/code_builder-4.6.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${collection} $out/hosted/pub.dev/collection-1.18.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${convert} $out/hosted/pub.dev/convert-3.1.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${coverage} $out/hosted/pub.dev/coverage-1.6.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${crypto} $out/hosted/pub.dev/crypto-3.0.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${cryptography} $out/hosted/pub.dev/cryptography-2.5.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${dart_style} $out/hosted/pub.dev/dart_style-2.3.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${file} $out/hosted/pub.dev/file-6.1.4

    mkdir -p $out/hosted/pub.dev
    ln -s ${fixnum} $out/hosted/pub.dev/fixnum-1.1.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${frontend_server_client} $out/hosted/pub.dev/frontend_server_client-3.2.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${glob} $out/hosted/pub.dev/glob-2.1.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${graphs} $out/hosted/pub.dev/graphs-2.3.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${hex} $out/hosted/pub.dev/hex-0.2.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${http_multi_server} $out/hosted/pub.dev/http_multi_server-3.2.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${http_parser} $out/hosted/pub.dev/http_parser-4.0.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${io} $out/hosted/pub.dev/io-1.0.4

    mkdir -p $out/hosted/pub.dev
    ln -s ${js} $out/hosted/pub.dev/js-0.6.7

    mkdir -p $out/hosted/pub.dev
    ln -s ${json_annotation} $out/hosted/pub.dev/json_annotation-4.8.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${json_serializable} $out/hosted/pub.dev/json_serializable-6.6.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${logging} $out/hosted/pub.dev/logging-1.2.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${matcher} $out/hosted/pub.dev/matcher-0.12.16

    mkdir -p $out/hosted/pub.dev
    ln -s ${meta} $out/hosted/pub.dev/meta-1.9.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${mime} $out/hosted/pub.dev/mime-1.0.4

    mkdir -p $out/hosted/git.polynom.me%47api%47packages%47Moxxy%47pub%47
    ln -s ${moxlib} $out/hosted/git.polynom.me%47api%47packages%47Moxxy%47pub%47/moxlib-0.2.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${node_preamble} $out/hosted/pub.dev/node_preamble-2.0.2

    mkdir -p $out/hosted/git.polynom.me%47api%47packages%47PapaTutuWawa%47pub%47
    ln -s ${omemo_dart} $out/hosted/git.polynom.me%47api%47packages%47PapaTutuWawa%47pub%47/omemo_dart-0.5.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${package_config} $out/hosted/pub.dev/package_config-2.1.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${path} $out/hosted/pub.dev/path-1.8.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${pedantic} $out/hosted/pub.dev/pedantic-1.11.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${petitparser} $out/hosted/pub.dev/petitparser-5.4.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${pinenacl} $out/hosted/pub.dev/pinenacl-0.5.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${pool} $out/hosted/pub.dev/pool-1.5.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${protobuf} $out/hosted/pub.dev/protobuf-2.1.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${protoc_plugin} $out/hosted/pub.dev/protoc_plugin-20.0.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${pub_semver} $out/hosted/pub.dev/pub_semver-2.1.4

    mkdir -p $out/hosted/pub.dev
    ln -s ${pubspec_parse} $out/hosted/pub.dev/pubspec_parse-1.2.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${random_string} $out/hosted/pub.dev/random_string-2.3.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${saslprep} $out/hosted/pub.dev/saslprep-1.0.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${shelf} $out/hosted/pub.dev/shelf-1.4.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${shelf_packages_handler} $out/hosted/pub.dev/shelf_packages_handler-3.0.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${shelf_static} $out/hosted/pub.dev/shelf_static-1.1.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${shelf_web_socket} $out/hosted/pub.dev/shelf_web_socket-1.0.4

    mkdir -p $out/hosted/pub.dev
    ln -s ${source_gen} $out/hosted/pub.dev/source_gen-1.3.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${source_helper} $out/hosted/pub.dev/source_helper-1.3.4

    mkdir -p $out/hosted/pub.dev
    ln -s ${source_map_stack_trace} $out/hosted/pub.dev/source_map_stack_trace-2.1.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${source_maps} $out/hosted/pub.dev/source_maps-0.10.12

    mkdir -p $out/hosted/pub.dev
    ln -s ${source_span} $out/hosted/pub.dev/source_span-1.10.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${stack_trace} $out/hosted/pub.dev/stack_trace-1.11.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${stream_channel} $out/hosted/pub.dev/stream_channel-2.1.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${stream_transform} $out/hosted/pub.dev/stream_transform-2.1.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${string_scanner} $out/hosted/pub.dev/string_scanner-1.2.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${synchronized} $out/hosted/pub.dev/synchronized-3.1.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${term_glyph} $out/hosted/pub.dev/term_glyph-1.2.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${test} $out/hosted/pub.dev/test-1.24.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${test_api} $out/hosted/pub.dev/test_api-0.6.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${test_core} $out/hosted/pub.dev/test_core-0.5.3

    mkdir -p $out/hosted/pub.dev
    ln -s ${timing} $out/hosted/pub.dev/timing-1.0.1

    mkdir -p $out/hosted/pub.dev
    ln -s ${typed_data} $out/hosted/pub.dev/typed_data-1.3.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${unorm_dart} $out/hosted/pub.dev/unorm_dart-0.2.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${uuid} $out/hosted/pub.dev/uuid-3.0.7

    mkdir -p $out/hosted/pub.dev
    ln -s ${very_good_analysis} $out/hosted/pub.dev/very_good_analysis-3.1.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${vm_service} $out/hosted/pub.dev/vm_service-11.10.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${watcher} $out/hosted/pub.dev/watcher-1.0.2

    mkdir -p $out/hosted/pub.dev
    ln -s ${web_socket_channel} $out/hosted/pub.dev/web_socket_channel-2.4.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${webkit_inspection_protocol} $out/hosted/pub.dev/webkit_inspection_protocol-1.2.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${xml} $out/hosted/pub.dev/xml-6.3.0

    mkdir -p $out/hosted/pub.dev
    ln -s ${yaml} $out/hosted/pub.dev/yaml-3.1.2
'';

}