when:
  branch: master

pipeline:
  # Check moxxmpp
  moxxmpp-lint:
    image: dart:3.0.7
    commands:
      - cd packages/moxxmpp
      # Proxy requests to pub.dev using pubcached
      - PUB_HOSTED_URL=http://172.17.0.1:8000 dart pub get
      - dart analyze --fatal-infos --fatal-warnings

  moxxmpp-test:
    image: dart:3.0.7
    commands:
      - cd packages/moxxmpp
      # Proxy requests to pub.dev using pubcached
      - PUB_HOSTED_URL=http://172.17.0.1:8000 dart pub get
      - dart test

  # Check moxxmpp_socket_tcp
  moxxmpp_socket_tcp-lint:
    image: dart:3.0.7
    commands:
      - cd packages/moxxmpp_socket_tcp
      # Proxy requests to pub.dev using pubcached
      - PUB_HOSTED_URL=http://172.17.0.1:8000 dart pub get
      - dart analyze --fatal-infos --fatal-warnings

  # moxxmpp-test:
  #   image: dart:3.0.7
  #   commands:
  #     - cd packages/moxxmpp
  #     # Proxy requests to pub.dev using pubcached
  #     - PUB_HOSTED_URL=http://172.17.0.1:8000 dart pub get
  #     - dart test

  notify:
    image: git.polynom.me/papatutuwawa/woodpecker-xmpp
    settings:
      xmpp_tls: 1
      xmpp_is_muc: 1
      xmpp_recipient: moxxy-build@muc.moxxy.org
      xmpp_alias: 2Bot
    secrets: [ xmpp_jid, xmpp_password, xmpp_server ]
    when:
      status:
        - failure
