name: integration_tests
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  moxxmpp: 0.2.0
  moxxmpp_socket_tcp: 0.2.1
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  very_good_analysis: ^3.0.1
