name: integration_tests
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  logging: ^1.3.0
  moxxmpp:
    path: ../packages/moxxmpp
  moxxmpp_socket_tcp:
    path: ../packages/moxxmpp_socket_tcp

dev_dependencies:
  build_runner: ^2.4.13
  test: ^1.25.8
  very_good_analysis: ^6.0.0
