name: moxxmpp_color
description: Implementation of XEP-0392
version: 0.1.0
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cryptography: ^2.7.0
  flutter:
    sdk: flutter
  hsluv: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
