name: moxxmpp
description: A pure-Dart XMPP library
version: 0.1.0
homepage: https://codeberg.org/moxxy/moxxmpp

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cryptography: 2.0.5
  hex: 0.2.0
  logging: 1.0.2
  moxlib:
   hosted: https://git.polynom.me/api/packages/Moxxy/pub
   version: 0.1.5
  omemo_dart:
   hosted: https://git.polynom.me/api/packages/PapaTutuWawa/pub
   version: 0.3.1
  random_string: 2.3.1
  saslprep: 1.0.2
  uuid: 3.0.5
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  meta: ^1.7.0
  test: ^1.16.0
  very_good_analysis: ^3.0.1

dependency_overrides:
  omemo_dart:
    git:
      url: https://codeberg.org/PapaTutuWawa/omemo_dart.git
      rev: c68471349ab1b347ec9ad54651265710842c50b7
